import assert from "node:assert/strict";
import { extractBpmnXml, isLikelyBpmn, isEditInstruction, safeFilename, renderMarkdown } from "../js/utils.js";
import { auditOfflineBpmn, generateOfflineBpmn, sopOfflineBpmn } from "../js/offline-service.js";
import { PROVIDERS, getProvider, providerOptions } from "../js/providers.js";

const xml = `<?xml version="1.0"?><bpmn:definitions><bpmn:process></bpmn:process><bpmndi:BPMNDiagram></bpmndi:BPMNDiagram></bpmn:definitions>`;
assert.equal(extractBpmnXml(`\`\`\`xml\n${xml}\n\`\`\``), xml);
assert.equal(extractBpmnXml(JSON.stringify({ bpmn_xml: xml })), xml);
assert.equal(isLikelyBpmn(xml), true);
assert.equal(isLikelyBpmn("<xml />"), false);
assert.equal(safeFilename("Customer Onboarding!", "bpmn"), "customer-onboarding.bpmn");
assert.equal(isEditInstruction("Add an approval task after review"), true);
assert.equal(isEditInstruction("افزودن مرحله تایید مدیر بعد از بررسی"), true);
assert.equal(isEditInstruction("Customer refund process"), false);
assert.equal(isEditInstruction("فرایند بازپرداخت مشتری"), false);
assert.match(renderMarkdown("## Health\n- Strong\n- **Fast**"), /<h2>Health<\/h2><ul><li>Strong<\/li><li><strong>Fast<\/strong><\/li><\/ul>/);
const offline = generateOfflineBpmn("Customer refund process");
assert.equal(isLikelyBpmn(offline), true);
assert.match(offline, /name="Customer refund process"/);
assert.match(auditOfflineBpmn(offline, "en"), /Customer refund process/);
assert.match(sopOfflineBpmn(offline, "en"), /Capture request details/);
assert.deepEqual(Object.keys(PROVIDERS), ["openai", "anthropic", "openrouter", "groq", "deepseek", "gemini", "mistral", "custom"]);
assert.equal(providerOptions().length, 8);
assert.equal(getProvider("unknown"), PROVIDERS.openai);
assert.match(PROVIDERS.openrouter.endpoint, /^https:\/\/openrouter\.ai\/api\/v1\/chat\/completions$/);
assert.match(PROVIDERS.groq.endpoint, /^https:\/\/api\.groq\.com\/openai\/v1\/chat\/completions$/);
assert.match(PROVIDERS.deepseek.endpoint, /^https:\/\/api\.deepseek\.com\/chat\/completions$/);
assert.equal(PROVIDERS.gemini.adapter, "gemini");
assert.equal(PROVIDERS.anthropic.adapter, "anthropic");
console.log("utils tests passed");
